version: "3.9"

services:
  microservice:
    image: greeting-microservice:v1
    container_name: greeting-micro
    build:
      context: .
    #      dockerfile: Dockerfile
    ports:
      - 9090:9090
    networks:
      - microservice-grpc

networks:
  microservice-grpc:
    external: true

